language: python
cache: pip
python:
  - "2.7"
  - "3.6"
addons:
    postgresql: "9.6"
services:
  - postgresql
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt"
script:
  - flake8
  - py.test

matrix:
  include:
    # Create docker image on merge to develop
    - python: "2.7"
      sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/gates-subscription-mapper:develop
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "ZMq+1ORpaqJwv58AcTApyKsqWkW3nOm5f8PErpJlbNNScS0HuY/jPJsY1kFTtzDvs8Bqjn68qoJ63VUxdukuoTnlmjy+fwjxB3UGQ8YZSamaJRXn6tB+fjzgOChg7xycCHsfuRPErsyOfUcinaNyH45LDiF7vHbMpm/WfjBuzm6nwmc3r4j98kOQKMJ7HCbiW4QDtv8T5k8ppGedXzbY9SE6Xlch//IgxI4mlFzKizemWXiPT0Ear50vVNkoUw0/ZzUbZF1GXjl55Vxc/u7fhGtPOcGYScNvGwNSaIqSd6CNb94XWTTv9AUBd8lgLPEmAHzP0NXrWUdjQwCSgZ7En6XytSULAg0Xt1IasD+abCz8uNCYXcHfebmyKY5f8CJ25kpEAZPGsPZK2eWyz8Uig+zEwQJqjWNRBxpQpRNme8e5E2rjp7+MMbg5LO5bzLmt7UgU8kbD6hSK454EgO/juylHLuIbm/frLmAYuEvL0nc5SnClVMPcFrpmQEPq5uakjlPh9BmoUrGXH1nTD9P3zQ0U+SSk3QpE6A+1OZyc7GYm3kV5rCPOb4+bZhOFgGvHHJMpL4n3yNne0z5XfuA+H9xeaJFZ3D2yS+sXQ3sIXbHeVDt0U6Of4yVOppCNfbwO3QUFJ+oQaJfQN5ncuSM2drTCA7bJrEEv/UdmXOv2pjs="
      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .
      
      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        provider: script
        script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"
        on:
          branch: develop
      
      # Inherited build steps that we don't want
      install: []
      addons: {}

    # Create versioned docker image on new version tag
    - python: "2.7"
      sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/gates-subscription-mapper
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "ZMq+1ORpaqJwv58AcTApyKsqWkW3nOm5f8PErpJlbNNScS0HuY/jPJsY1kFTtzDvs8Bqjn68qoJ63VUxdukuoTnlmjy+fwjxB3UGQ8YZSamaJRXn6tB+fjzgOChg7xycCHsfuRPErsyOfUcinaNyH45LDiF7vHbMpm/WfjBuzm6nwmc3r4j98kOQKMJ7HCbiW4QDtv8T5k8ppGedXzbY9SE6Xlch//IgxI4mlFzKizemWXiPT0Ear50vVNkoUw0/ZzUbZF1GXjl55Vxc/u7fhGtPOcGYScNvGwNSaIqSd6CNb94XWTTv9AUBd8lgLPEmAHzP0NXrWUdjQwCSgZ7En6XytSULAg0Xt1IasD+abCz8uNCYXcHfebmyKY5f8CJ25kpEAZPGsPZK2eWyz8Uig+zEwQJqjWNRBxpQpRNme8e5E2rjp7+MMbg5LO5bzLmt7UgU8kbD6hSK454EgO/juylHLuIbm/frLmAYuEvL0nc5SnClVMPcFrpmQEPq5uakjlPh9BmoUrGXH1nTD9P3zQ0U+SSk3QpE6A+1OZyc7GYm3kV5rCPOb4+bZhOFgGvHHJMpL4n3yNne0z5XfuA+H9xeaJFZ3D2yS+sXQ3sIXbHeVDt0U6Of4yVOppCNfbwO3QUFJ+oQaJfQN5ncuSM2drTCA7bJrEEv/UdmXOv2pjs="
      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .
      
      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        provider: script
        script: dcd --version "$(git tag -l --points-at HEAD)" --version-semver --version-latest "$IMAGE_NAME"
        on:
          tags: true
      
      # Inherited build steps that we don't want
      install: []
      addons: {}
