# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrateSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.TextField(blank=True, null=True, unique=True, verbose_name='Task ID of the Task')),
                ('status', models.CharField(choices=[('S', 'Starting'), ('R', 'Running'), ('E', 'Error'), ('C', 'Complete')], default='S', max_length=1, verbose_name='Status of the task')),
                ('from_messageset', models.IntegerField(verbose_name='ID of the messageset to transfer subscriptions from')),
                ('to_messageset', models.IntegerField(verbose_name='ID of the messageset to transfer subscriptions to')),
                ('table_name', models.TextField(verbose_name='Database table for identity IDs')),
                ('column_name', models.TextField(verbose_name='Column in table for identity IDs')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Total number of identities to process')),
                ('current', models.IntegerField(default=0, verbose_name='Current count of processed identities')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
