# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migratesubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='migratesubscription',
            index=models.Index(fields=['-created_at'], name='mapper_migr_created_4250d1_idx'),
        ),
    ]
