# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20170810_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.IntegerField(choices=[(50, 'Critical'), (40, 'Error'), (30, 'Warning'), (20, 'Info'), (10, 'Debug'), (0, 'Not Set')], default=20, verbose_name='Log Level')),
                ('message', models.TextField(verbose_name='Log Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('migrate_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mapper.MigrateSubscription')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='logevent',
            index=models.Index(fields=['migrate_subscription', 'created_at'], name='mapper_loge_migrate_fbd5ef_idx'),
        ),
    ]
