# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_auto_20170815_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migratesubscription',
            name='status',
            field=models.CharField(choices=[('S', 'Starting'), ('R', 'Running'), ('D', 'Cancelled'), ('E', 'Error'), ('C', 'Complete')], default='S', max_length=1, verbose_name='Status of the task'),
        ),
    ]
