# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0005_auto_20170825_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevertedIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('migrate_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverted_identities', to='mapper.MigrateSubscription')),
            ],
            options={
                'verbose_name_plural': 'reverted identities',
            },
        ),
        migrations.AlterModelOptions(
            name='migratedidentity',
            options={'verbose_name_plural': 'migrated identities'},
        ),
        migrations.AddField(
            model_name='migratedidentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='migratedidentity',
            name='migrate_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrated_identities', to='mapper.MigrateSubscription'),
        ),
        migrations.AddIndex(
            model_name='revertedidentity',
            index=models.Index(fields=['identity_uuid'], name='mapper_reve_identit_544d53_idx'),
        ),
    ]
